Add sanity test for servicenow.itsm
ansible/project-config pull request #791
Opened 2021-04-05 09:02 UTC by Akasurde

Depends-On: ansible/ansible-zuul-jobs#856

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

2021-04-05 16:16 UTC, Akasurde commented
recheck

2021-04-05 19:44 UTC, GomathiselviS requested changes

2021-04-05 19:44 UTC, GomathiselviS commented on zuul.d/projects.yaml
> +      - ansible-collections-servicenow-itsm-sanity
This has to be ansible-collections-servicenow-itsm-units

2021-04-07 11:56 UTC, merged

2021-04-07 12:29 UTC, Akasurde commented
@pabelanger @GomathiselviS Thanks for the review and merge.